package ai.openclaw.android.speaker.model

/**
 * Speaker ID model
 * Generated by Gateway based on voiceprint feature hash
 */
data class SpeakerId(
    val id: String,              // Full ID, e.g., "spk_a3f7b2_M"
    val hash: String,            // Voiceprint feature hash
    val gender: String?,         // M/F/U
    val registeredAt: Long       // Registration timestamp
) {
    companion object {
        const val PREFIX = "spk_"
        const val UNKNOWN_PREFIX = "spk_unknown_"

        fun isValid(id: String): Boolean {
            return id.startsWith(PREFIX) && !id.startsWith(UNKNOWN_PREFIX)
        }

        fun isUnknown(id: String): Boolean {
            return id.startsWith(UNKNOWN_PREFIX)
        }
    }
}
